security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\TombolaAuthenticator

            access_denied_url: /email-not-verified

            logout:
                path: app_logout

    access_control:
        # Accès à l'administration
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Accès au profil
        - { path: ^/profile, roles: ROLE_USER }

        # Accès aux commandes, seulement si l'email est vérifié
        - { path: ^/order, roles: ROLE_USER, allow_if: "is_granted('ROLE_USER') and user.isEmailVerified()" }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
