services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Désactiver l'autowiring pour PayPalService et le rendre public
    App\Service\PayPalService:
        public: true
        autowire: false
        arguments:
            $clientId: '%env(string:PAYPAL_CLIENT_ID)%'
            $secret: '%env(string:PAYPAL_SECRET)%'
            $mode: '%env(string:PAYPAL_MODE)%'

